version: '2.1'
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=web_customer_tracker
      - MYSQL_ROOT_PASSWORD=XCkvZg6RHZ
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - '3306'
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'

  web:
    build:
      context: ../../../out/artifacts
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'
    links:
      - "db"
    depends_on:
      db:
        condition: service_healthy
    restart: always


